//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class expense1
    {
        public int ID { get; set; }

        [Required]
        [StringLength(20, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 3)]

        public string ExpenseName { get; set; }
        
        [ForeignKey("expensecate")]
        [Required(ErrorMessage ="Please Select  Valid Category")]
        public Nullable<int> ExpenseCategoryID { get; set; }

        [Required (ErrorMessage =" value 1 to 100000 ")]

        public int ExpensePrice { get; set; }

        [Required(ErrorMessage ="Date Method dd-mm-yy")]
        public System.DateTime ExpenseDate { get; set; }

       
        public string ExpenseDescription { get; set; }

      

        public virtual expensecate expensecate { get; set; }
    }
}
